config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      get :update_status
      get :cancel_order
      get :show_partial
    end  
  end  


  resources :items
  resources :restaurants
  resources :areas
  resources :cities

# get "/order/show_partial", to: "orders#show_partial"
  
 get '/restaurant_items', to: 'items#restaurant_items',as:'restaurant_items'
	# devise_scope :user do
	# 	root to: "devise/sessions#new"
	# end
	root "landing_page#index"
  devise_for :users


  Rails.application.routes.draw do
  get "/landing_page/admin", to: "landing_page#admin", as: "admin"
  get "/landing_page/user", to: "landing_page#user", as: "user"
  get "/landing_page/resto", to: "landing_page#resto", as: "resto"

  get "/landing_page/filter_areas", to: "landing_page#filter_areas"
  
  
  # root 'homes#index'
  # devise_scope :user do
  #   authenticated :user do
  #     # root :to => 'homes#cashier_option'
  #   end
  # end
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  belongs_to :user
   belongs_to :restaurant
   # validates :name, presence: true
   # validates :address, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :update_status, :cancel_order, :show_partial]

  def index
      if current_user.role_id ==1
        @orders = Order.all
      else
        @orders = current_user&.restaurant&.orders
      end
      end

  def cancel_order
    #binding.pry
    @order.destroy
     respond_to do |format|
       format.html { redirect_to root_url, notice: 'Order was successfully cancelled.' }
       format.json { head :no_content }
     end
  end

  
  def show
    @order = Order.find(params[:id]) 
  end
  

  def update_status
    #binding.pry
    @order = Order.find(params[:id])
    @order.status = params[:status]
    @order.save
    redirect_to orders_path
  end

   def show_partial
    @order = Order.find(params[:id])
    return render @order
  end
 
  def new
    
    @id = params[:id]
    @item = Item.find(@id)
    @order = Order.new
  end

  
  def edit
  end

  def create
    
    @order = Order.new
    @order.item_id = params[:order][:item_id]
    @order.name = params[:order][:name]
    @order.address = params[:order][:address]
    @order.email = params[:order][:email]
    @order.mobile = params[:order][:mobile]
    @order.quantity = params[:order][:quantity]
    @order.restaurant_id = params[:order][:restaurant_id]
    @order.user_id = current_user.id
    @order.total_price = params[:order][:quantity].to_i * params[:order][:up].to_i
     # respond_to do |format|
     # binding.pry
      if @order.save
        OrderMailer.new_order(@order).deliver_now
      redirect_to order_path(:id => @order.id)
    else
      redirect_to orders_path
    end
  end

       
  #       format.html { redirect_to @order, notice: 'Order was successfully created.' }
  #       format.json { render :show, status: :created, location: @order }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @order.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
    

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

   def destroy
     @order.destroy
     respond_to do |format|
       format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
       format.json { head :no_content }
     end
   end

  private
  
    def set_order
      @order = Order.find(params[:id])
    end

   
     def order_params
       params.require(:order).permit(:name, :address, :email, :mobile, :quantity, :total_price, :item_id, :restaurant_id, :status)
     end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true, item: @item, :html=>{:id=>"form_id"}) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>


      <ul>
 
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

<!--   <div class="field">
    <strong><label>Restaurant-name:-> <%#= @order.restaurant.name %></label></strong>
  </div> -->
     
    <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: "name" , required: true%>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: "address" , required: true%>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: "email" , required: true%>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, id:"mobile", required: true %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity,id: "quantity", onchange:"testMethod(this)" , required: true, min: 1%>
  </div>

  <div class="field">
    <strong><label> Price : <%= @item.price %></label><b id ="unitprice"></b></strong>
  </div>

  <div class="field">
     <strong><label> Total_Price :<b id ="totalprice"></b>
        </strong></label>
  </div>

    <%= form.hidden_field :item_id,  value: @item.id%>
    <%= form.hidden_field :up,  value: @item.price%>
    <%= form.hidden_field :restaurant_id,  value: params[:restaurant_id] %> 

  <div class="actions">

    <%= form.submit %>
  </div>
<% end %>

<script type="text/javascript">
  function testMethod(element){
    var item_quantity = element.value;
    var unit_price = "<%= @item.price %>"
    $("#totalprice").html(parseInt(item_quantity)*parseInt(unit_price));
  }
</script>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Orders</h1>


<table class="table table-hover">
  <thead class="thead thead-dark">
    <tr class="table-info">
      
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Quantity</th>
      <th>Total price</th>
      <th>Item</th>
 
      <th colspan="3">Actions</th> 
    </tr>
  </thead>

  <tbody>
    <% @orders&.each do |order| %>
      <tr class="table-info">
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.mobile %></td>
        <td><%= order.quantity %></td>
        <td><%= order.total_price %></td>
        <td><%= order.item.name %></td>
       <!--  <td><%#= link_to 'Show', order  if current_user.role_id == User::USER_ROLES["User"] %></td> %></td> -->
        <%#= link_to 'Edit', edit_order_path(order) if current_user.role_id == User::USER_ROLES["Admin"] %><!-- 
        <td><%#= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } if current_user.role_id == User::USER_ROLES["Resto"] %></td> -->
     
         <td><%= link_to 'accept', update_status_order_path(id: order.id, status: 'confirmed'),  :class=>"btn btn-success" %></td>
          
         <td><%= link_to 'reject', update_status_order_path(id: order.id, status: 'rejected'), :class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<center><h1 class= "s">Order Details </h1></center>

<%= render 'form', order: @order %>

<%#= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<center><p id="notice"><%= notice %></p>
<h1>your order is placed successfully, it will be delivered shortly</h1>


<p>
   <strong>Order_id:</strong>
  <%= @order.id %>
<p> 

<p>
   <strong>Status:</strong>
  <%= @order.status %>
<p> 

<p>
  <strong>Restaurant name:</strong>
  <%= @order.item.restaurant.name %>
</p>

<p>
  <strong>Item name:</strong>
  <%= @order.item.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @order.mobile %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @order.total_price %>
</p>



<!-- 
  <strong>Item name:</strong>
  <%= @order.item.name %>
</p>
</center> -->




<%#= link_to 'Edit', edit_order_path(@order) %> 
<%#= link_to 'Back', orders_path %>
<td><%= link_to 'Cancel Order',   cancel_order_order_path,{:class=>"btn btn-danger" } %></td>




<script>
$(document).ready(function() {
 setInterval(function() {
          $.ajax({
          type: 'GET',
          url: '<%= url_for(:action => 'show_partial', :id => @order) %>',
          data: {},
          cache: false,
          success: function(result) {
               // $('#show_partial').html(result)
          }
      });


  }, 2000);

});
</script>

app/views/orders/show_partial.js.erb
$('#show_partial').html('<%= escape_javascript (render @order) %>')