config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      get :update_status
      get :cancel_order
      get :show_partial
    end  
  end  


  resources :items
  resources :restaurants
  resources :areas
  resources :cities

# get "/order/show_partial", to: "orders#show_partial"
  
 get '/restaurant_items', to: 'items#restaurant_items',as:'restaurant_items'
	# devise_scope :user do
	# 	root to: "devise/sessions#new"
	# end
	root "landing_page#index"
  devise_for :users


  Rails.application.routes.draw do
  get "/landing_page/admin", to: "landing_page#admin", as: "admin"
  get "/landing_page/user", to: "landing_page#user", as: "user"
  get "/landing_page/resto", to: "landing_page#resto", as: "resto"

  get "/landing_page/filter_areas", to: "landing_page#filter_areas"
  
  
  # root 'homes#index'
  # devise_scope :user do
  #   authenticated :user do
  #     # root :to => 'homes#cashier_option'
  #   end
  # end
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
	before_action :authenticate_user!
	def index
		@cities = City.all
		@areas = Area.all
	end

	def  admin;
		@restaurants = Restaurant.all.count
		@orders  = Order.all.count
    end

  def user
  	@cities = City.all
		@areas = Area.all
  end
   

  def resto
  end  
  
  def filter_areas
  end
	
end

app/views/landing_page/admin.html.erb
<%if current_user.role_id == 1%><h1><font color="black"><h1 class="shrey">Food Online</h1></font></h1>


	  <td><%= link_to 'New City', new_city_path,{:class=>"btn btn-danger" } %></td>
	  <td><%= link_to 'New Area', new_area_path,{:class=>"btn btn-danger" } %></td>
	<td><%= link_to 'New Restaurant', new_restaurant_path,{:class=>"btn btn-danger" } %></td>
	<%#= link_to 'New Item', new_item_path,{:class=>"btn btn-danger" } %>


	<td><%= link_to 'Restaurants', restaurants_path,{:class=>"btn btn-danger" } %></td>

	<td><%= link_to 'Items', items_path,{:class=>"btn btn-danger" } %></td>

	<!-- <td><%#= link_to 'items', restaurant_items_path,{:class=>"btn btn-primary" } %></td> -->
		<td><%= link_to 'Orders', orders_path,{:class=>"btn btn-danger" } %></td>

  



  <div align="center">
<h1>Dashboard</h1>
<div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800" align="center"></h1>
          </div>

        <div class="row">


           <i class="fa fa-appointment" aria-hidden="true" style="font-size:36px"></i>
            <div class="">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-secondary text-uppercase mb-1" align="center">Total Orders</div>
                      <div class="h3 mb-0 font-weight-bold text-gray-800" align="center"><h3 class="text-warning"><%= @orders %></h3></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <!-- <i class="fa fa-list-alt" aria-hidden="true" style="font-size:36px"></i>
            <div class="circle">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-secondary  text-uppercase mb-1" align="center">Total Items</div>
                      <div class="h3 mb-0 font-weight-bold text-gray-800" align="center"><h3 class="text-warning"><%= @items %></h3></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div> -->
         <i class="fa fa-list-alt" aria-hidden="true" style="font-size:36px"></i>
            <div class="circle">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-secondary  text-uppercase mb-1" align="center">Total Restaurants </div>
                      <div class="h3 mb-0 font-weight-bold text-gray-800" align="center"><h3 class="text-warning"><%= @restaurants %></h3></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
</div>




<%else%>
	<h1>Sorry you are not admin</h1>
<%end%>

app/views/landing_page/filter_areas.js.erb
<% cities = City.find(params[:cities]).areas.pluck(:name, :id) %>
$('#restaurant_areas').html("<%= escape_javascript(options_for_select(cities)) %>");

app/views/landing_page/index.html.erb
<html>
<header>
   
<h1><font color="red"><h1 class="shishanshu"><marquee>Food Online</marquee></h1></font></h1>
<font size="5" color="blue">
  <div class="form">
  </header>

</div>
  
<%= form_for :restaurant, :url => restaurants_path(), method: :get do |f| %>            
       

<label class="cities-label">Cities

<% cities_arr = @cities.all.pluck("name","id")%>
       <%= select_tag(
          'cities',
          options_for_select(
           @cities.all.pluck("name","id")
          ),
          data: {
            remote: true,
            url: 'landing_page/filter_areas',
            method: 'get'
          }
        ) %>
      </label>
    
    <label class="areas-label">Areas
<%areas_arr = @areas.all.pluck("name","id")%>
       <%= f.select("areas", areas_arr)%>
    </label>
    <div class="search">
       <%= f.submit "search" , :class=> "btn  btn-lg btn-danger"%>
     </div>
     </font>
<% end %>
<style >



  label.cities-label{
    margin-right: 10px;
   top: 210px;

  }

  .areas-label{
    position: absolute;
    left: 250px;
    top: 240px;
  
  margin-right: 10px;
  }
  .search{
    position: absolute;
    top:280px;
    left: 500px;

  }
</style>
</html>

app/views/landing_page/resto.html.erb
<h1><font color="red"><h1 class="sss">Food Online</h1></font></h1>
<br>
<br>


<td><%= link_to 'New Item', new_item_path,{:class=>"btn btn-default" } %></td>





<td><%= link_to ' orders', orders_path,{:class=>"btn btn-default" } %></td>

<td><%= link_to 'Items', items_path,{:class=>"btn btn-default" } %></td>