config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      get :update_status
      get :cancel_order
      get :show_partial
    end  
  end  


  resources :items
  resources :restaurants
  resources :areas
  resources :cities

# get "/order/show_partial", to: "orders#show_partial"
  
 get '/restaurant_items', to: 'items#restaurant_items',as:'restaurant_items'
	# devise_scope :user do
	# 	root to: "devise/sessions#new"
	# end
	root "landing_page#index"
  devise_for :users


  Rails.application.routes.draw do
  get "/landing_page/admin", to: "landing_page#admin", as: "admin"
  get "/landing_page/user", to: "landing_page#user", as: "user"
  get "/landing_page/resto", to: "landing_page#resto", as: "resto"

  get "/landing_page/filter_areas", to: "landing_page#filter_areas"
  
  
  # root 'homes#index'
  # devise_scope :user do
  #   authenticated :user do
  #     # root :to => 'homes#cashier_option'
  #   end
  # end
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :area
  belongs_to :user
  has_many :items
  has_many :orders
  mount_uploader :image,ImageUploader
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

 
  def index    
    if params[:restaurant].present?
     @restaurants = Restaurant.where(area_id: params[:restaurant][:areas])
   else
    @restaurants = Restaurant.all
   end

  end

  def show
  end

  def new
    # @areas_obj = Area.all.pluck("name", "id")
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  def create
     password = (0...8).map { ('a'..'z').to_a[rand(26)] }.join

  user = User.new(email: params[:email], password: password, password_confirmation: password, role_id: 3)
  if user.save
     
     restaurant = user.build_restaurant(restaurant_params)
    # respond_to do |format|
      if restaurant.save
       
        RestaurantMailer.owner_greeting(params[:email], password).deliver_now
          redirect_to admin_path
          # format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
          # format.json { render :show, status: :created, location: @restaurant }
       else
         redirect_to restaurants_path
       
    end
    end
  
  end
  

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
  
      params.require(:restaurant).permit(:name, :description, :image, :area_id, :user_id)
    end
  

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :email %>
    <%= text_field_tag :email %>
  </div>



  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
    
  </div>

  <div class="field">
    <%= form.label :area_id %>
    <%= form.select(:area_id, Area.all.collect {|p| [ p.name, p.id ] }) %>
  </div>


 <!-- <div class="field">
    <%= form.label :user_id %>
      <%= form.text_field :user_id %>
  </div>
 -->
  <%#= form.hidden_field :user_id,  value: @user.id%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>
   
<center><font color="black"><h1 class="pt">Restaurants</h1></font></center>

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
    <th>Description</th> 
       <th>Image</th>
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody> --> 
    
    <% @restaurants.in_groups_of(3).each do |restaurants| %>
    <div class = "row">
      <% restaurants.each do |restaurant| %>
    <%next if restaurant.blank?%>
    <div class = "col-md-4">
        <%#= restaurant.name %>
        <%#= restaurant.description %>
        <%if restaurant.image.url.present?%>
       <%=link_to image_tag(restaurant.image.url,:class=>"restaurant"), restaurant_items_path(id:restaurant.id) %><br>
        <% end -%>
          <%= link_to restaurant_items_path(:id => restaurant.id),{:class=>"btn btn-primary" } do %>
          <div class="category"><%= restaurant.name %></div>
          <%end%>
          <% if current_user.role_id ==1 %>
       <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>

         <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td> <%= link_to 'New Restaurant', new_restaurant_path %></td>
         <% end %>
      </div>
      <% end %>
      <br>

<br>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%if current_user.role_id == 1%>
<%= render 'form', restaurant: @restaurant %>

<%#= link_to 'Back', restaurants_path %>
<%end%>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @restaurant.image.url,size: "200x200"%>
</p>


<p>
  <strong>Area:</strong>
  <%= @restaurant.area_id %>
</p>


<p>
  <strong>User:</strong>
  <%= @restaurant.user_id %>
</p>
<p>
  <strong>Email:</strong>
  <%= @email %>
</p>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>