config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      get :update_status
      get :cancel_order
      get :show_partial
    end  
  end  


  resources :items
  resources :restaurants
  resources :areas
  resources :cities

# get "/order/show_partial", to: "orders#show_partial"
  
 get '/restaurant_items', to: 'items#restaurant_items',as:'restaurant_items'
	# devise_scope :user do
	# 	root to: "devise/sessions#new"
	# end
	root "landing_page#index"
  devise_for :users


  Rails.application.routes.draw do
  get "/landing_page/admin", to: "landing_page#admin", as: "admin"
  get "/landing_page/user", to: "landing_page#user", as: "user"
  get "/landing_page/resto", to: "landing_page#resto", as: "resto"

  get "/landing_page/filter_areas", to: "landing_page#filter_areas"
  
  
  # root 'homes#index'
  # devise_scope :user do
  #   authenticated :user do
  #     # root :to => 'homes#cashier_option'
  #   end
  # end
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :restaurant
  has_many :orders
  mount_uploader :image,ImageUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(restaurant_id: current_user.restaurant.id)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end
  
  def restaurant_items
    restaurant = Restaurant.where(id: params[:id])
    @items = restaurant.last.items if restaurant.present?
  end

  # GET /items/new
  def new
    # @restaurants_obj = Restaurant.all.pluck("name", "id")
    if current_user.role_id ==3 || current_user.role_id ==1
    @item= Item.new
    @items = Item.where(restaurant_name: current_user.restaurant.name)
  end
end

  # GET /items/1/edit
  def edit
      
  end

  # POST /items
  # POST /items.json
  def create
     @item = Item.new(item_params)
    # @item.restaurant_id = Restaurant.where(:email current_user.email)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :image, :restaurant_id, :price)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
 

  <div class="field">
    <%= form.label :restaurant_id %>
    <%= form.select(:restaurant_id, Restaurant.all.collect {|p| [ p.name, p.id ] }) %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<h1 >Items</h1>

<table >
  <thead>
    <tr>
      <th>Name</th>
     <!--  <th>Description</th> -->
      <th>Image</th>
      <th>Price</th>
    <!--   <th>Restaurant</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
     <!--    <td><%= item.description %></td> -->

       <td><%if item.image.present?%><%= image_tag item.image.url, size: "200x200", :class=>"item" %><% end -%></td> 
          <td><%= item.price %></td>
       <% if current_user.role_id == 3 %>
        <%#= item.restaurant_id %>
        <td><%= link_to 'Show', item, :class=>"btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_item_path(item), :class=>"btn btn-success" %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' },  :class=>"btn btn-danger"  %></td>
          <% end%>
      </tr>
    <% end%>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%#= link_to 'Back', resto_path %>

app/views/items/restaurant_items.html.erb
 <p id="notice"><%= notice %></p>

<center><font color="black"><h1 class="sh">Items</h1></font></center>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <!-- <th>Description</th> -->
      <th>Image</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
   
      <tr>
        <td><%= item.name %></td>
     <!--    <td><%= item.description %></td> -->

       <td><%if item.image.present?%><%= image_tag item.image.url, size: "200x200", :class=>"item" %><% end -%></td> 
         
        <td><%= item.price %></td>
          <td><%= link_to 'Order', new_order_path(:id => item.id, restaurant_id: params[:id]),{:class=>"btn btn-danger" } %></td>

           <% if current_user.role_id ==1 %>
           <%# elsif current_user.role_id ==3 %>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%= link_to 'New Item', new_item_path %>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @item.image %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%#= link_to 'Back', items_path %>